### ISSUE TITLE
Follow Platform Component's Information From Platform Map

### ISSUE THREAD

**Issue by tunahanertekin** [robolaunch/central-orchestrator#76]
### What would you like to be added?

Details about platform components will be available [here](https://github.com/robolaunch/robolaunch/blob/main/platform.json). Orchestrator should use *latest production release* while creating & operating robolaunch Robotics Cloud.

### Why is this needed?

It's needed to track platform dependencies and provide consistency between Robotics Cloud components.

**Comment by Mert18** [comment]
Connection hub cloud instance, connection hub operator, cert manager, and robot operator are now fetched dynamically. Other components will be added as we go.
